version: '3'

services:
  scrapyd:
    build: .
    ports:
      - 6800:6800
    env_file:
      - ../.env.local
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: condo-database
    volumes:
      - .mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${MONGO_DB_DATA_PATH}:/data/db
    ports:
      - 27017:27017
      - 9229:9229
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8111:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=usr
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass

  mysql-db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'usr'
      MYSQL_PASSWORD: 'rootpass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ${SQL_DB_DATA_PATH}:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '3360:80'
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: rootpass

